-- =====================================================
-- PostgreSQL dump -- IFRI_MentorLink
-- Database version: 18.3
-- Generated: 2026-06-10
-- =====================================================

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- ######################################################
-- 1. USER & AUTH
-- ######################################################

CREATE TABLE gestion_comptes_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    telephone character varying(20),
    date_inscription timestamp with time zone NOT NULL
);

ALTER TABLE gestion_comptes_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gestion_comptes_user_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE gestion_comptes_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);

ALTER TABLE gestion_comptes_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gestion_comptes_user_groups_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE gestion_comptes_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);

ALTER TABLE gestion_comptes_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gestion_comptes_user_user_permissions_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- ######################################################
-- 2. PROFILE
-- ######################################################

CREATE TABLE gestion_comptes_profile (
    id bigint NOT NULL,
    filiere character varying(100),
    niveau character varying(50),
    competences text,
    lacunes text,
    disponibilites text,
    bio text,
    photo character varying(100),
    user_id bigint NOT NULL,
    sexe character varying(1) NOT NULL
);

ALTER TABLE gestion_comptes_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME gestion_comptes_profile_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- ######################################################
-- 3. PROPOSALS (offres/demandes)
-- ######################################################

CREATE TABLE backend_offres_demandes_proposal (
    id bigint NOT NULL,
    type character varying(10) NOT NULL,
    matiere character varying(100) NOT NULL,
    description text NOT NULL,
    disponibilite_debut timestamp with time zone NOT NULL,
    disponibilite_fin timestamp with time zone NOT NULL,
    modalite character varying(15) NOT NULL,
    statut character varying(10) NOT NULL,
    date_creation timestamp with time zone NOT NULL,
    auteur_id bigint NOT NULL
);

ALTER TABLE backend_offres_demandes_proposal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME backend_offres_demandes_proposal_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- ######################################################
-- 4. MATCHING
-- ######################################################

CREATE TABLE backend_matching_matching (
    id bigint NOT NULL,
    score integer NOT NULL,
    date timestamp with time zone NOT NULL,
    user1_id bigint NOT NULL,
    user2_id bigint NOT NULL,
    statut character varying(15) NOT NULL,
    matiere character varying(100) NOT NULL
);

ALTER TABLE backend_matching_matching ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME backend_matching_matching_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- ######################################################
-- 5. MESSAGERIE
-- ######################################################

CREATE TABLE backend_messagerie_conversation (
    id bigint NOT NULL,
    creee_le timestamp with time zone NOT NULL
);

ALTER TABLE backend_messagerie_conversation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME backend_messagerie_conversation_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE backend_messagerie_conversation_participants (
    id bigint NOT NULL,
    conversation_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE backend_messagerie_conversation_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME backend_messagerie_conversation_participants_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE backend_messagerie_message (
    id bigint NOT NULL,
    contenu text NOT NULL,
    envoye_le timestamp with time zone NOT NULL,
    lu boolean NOT NULL,
    conversation_id bigint NOT NULL,
    expediteur_id bigint NOT NULL
);

ALTER TABLE backend_messagerie_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME backend_messagerie_message_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- ######################################################
-- PRIMARY KEYS
-- ######################################################

ALTER TABLE ONLY gestion_comptes_user ADD CONSTRAINT gestion_comptes_user_pkey PRIMARY KEY (id);
ALTER TABLE ONLY gestion_comptes_user_groups ADD CONSTRAINT gestion_comptes_user_groups_pkey PRIMARY KEY (id);
ALTER TABLE ONLY gestion_comptes_user_user_permissions ADD CONSTRAINT gestion_comptes_user_user_permissions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY gestion_comptes_profile ADD CONSTRAINT gestion_comptes_profile_pkey PRIMARY KEY (id);
ALTER TABLE ONLY backend_offres_demandes_proposal ADD CONSTRAINT backend_offres_demandes_proposal_pkey PRIMARY KEY (id);
ALTER TABLE ONLY backend_matching_matching ADD CONSTRAINT backend_matching_matching_pkey PRIMARY KEY (id);
ALTER TABLE ONLY backend_messagerie_conversation ADD CONSTRAINT backend_messagerie_conversation_pkey PRIMARY KEY (id);
ALTER TABLE ONLY backend_messagerie_conversation_participants ADD CONSTRAINT backend_messagerie_conversation_participants_pkey PRIMARY KEY (id);
ALTER TABLE ONLY backend_messagerie_message ADD CONSTRAINT backend_messagerie_message_pkey PRIMARY KEY (id);

-- ######################################################
-- UNIQUE CONSTRAINTS
-- ######################################################

ALTER TABLE ONLY gestion_comptes_user ADD CONSTRAINT gestion_comptes_user_username_key UNIQUE (username);
ALTER TABLE ONLY gestion_comptes_user ADD CONSTRAINT gestion_comptes_user_email_key UNIQUE (email);
ALTER TABLE ONLY gestion_comptes_user ADD CONSTRAINT gestion_comptes_user_telephone_key UNIQUE (telephone);
ALTER TABLE ONLY gestion_comptes_profile ADD CONSTRAINT gestion_comptes_profile_user_id_key UNIQUE (user_id);
ALTER TABLE ONLY gestion_comptes_user_groups ADD CONSTRAINT gestion_comptes_user_groups_user_id_group_id_10316cce_uniq UNIQUE (user_id, group_id);
ALTER TABLE ONLY gestion_comptes_user_user_permissions ADD CONSTRAINT gestion_comptes_user_use_user_id_permission_id_a7cfa43e_uniq UNIQUE (user_id, permission_id);
ALTER TABLE ONLY backend_messagerie_conversation_participants ADD CONSTRAINT backend_messagerie_conve_conversation_id_user_id_8690c90f_uniq UNIQUE (conversation_id, user_id);

-- ######################################################
-- FOREIGN KEYS
-- ######################################################

ALTER TABLE ONLY gestion_comptes_profile
    ADD CONSTRAINT gestion_comptes_prof_user_id_3168b28b_fk_gestion_c
    FOREIGN KEY (user_id) REFERENCES gestion_comptes_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY backend_offres_demandes_proposal
    ADD CONSTRAINT backend_offres_deman_auteur_id_d30cc3a0_fk_gestion_c
    FOREIGN KEY (auteur_id) REFERENCES gestion_comptes_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY backend_matching_matching
    ADD CONSTRAINT backend_matching_mat_user1_id_e86d1697_fk_gestion_c
    FOREIGN KEY (user1_id) REFERENCES gestion_comptes_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY backend_matching_matching
    ADD CONSTRAINT backend_matching_mat_user2_id_883482b5_fk_gestion_c
    FOREIGN KEY (user2_id) REFERENCES gestion_comptes_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY backend_messagerie_conversation_participants
    ADD CONSTRAINT backend_messagerie_c_conversation_id_747b654c_fk_backend_m
    FOREIGN KEY (conversation_id) REFERENCES backend_messagerie_conversation(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY backend_messagerie_conversation_participants
    ADD CONSTRAINT backend_messagerie_c_user_id_0f9add7b_fk_gestion_c
    FOREIGN KEY (user_id) REFERENCES gestion_comptes_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY backend_messagerie_message
    ADD CONSTRAINT backend_messagerie_m_conversation_id_f2a2d6b5_fk_backend_m
    FOREIGN KEY (conversation_id) REFERENCES backend_messagerie_conversation(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY backend_messagerie_message
    ADD CONSTRAINT backend_messagerie_m_expediteur_id_ebd04520_fk_gestion_c
    FOREIGN KEY (expediteur_id) REFERENCES gestion_comptes_user(id) DEFERRABLE INITIALLY DEFERRED;

-- ######################################################
-- INDEXES
-- ######################################################

CREATE INDEX backend_matching_matching_user1_id_e86d1697 ON backend_matching_matching USING btree (user1_id);
CREATE INDEX backend_matching_matching_user2_id_883482b5 ON backend_matching_matching USING btree (user2_id);
CREATE INDEX backend_messagerie_message_conversation_id_f2a2d6b5 ON backend_messagerie_message USING btree (conversation_id);
CREATE INDEX backend_messagerie_message_expediteur_id_ebd04520 ON backend_messagerie_message USING btree (expediteur_id);
CREATE INDEX backend_offres_demandes_proposal_auteur_id_d30cc3a0 ON backend_offres_demandes_proposal USING btree (auteur_id);