# Generated by Django 6.0.6 on 2026-06-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='expediteur',
        ),
    ]
