# Generated by Django 6.0.6 on 2026-06-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('disponibilite_debut', models.DateTimeField()),
                ('disponibilite_fin', models.DateTimeField()),
                ('modalite', models.CharField(choices=[('PRESENTIEL', 'Présentiel'), ('DISTANCIEL', 'Distanciel'), ('HYBRIDE', 'Hybride')], default='PRESENTIEL', max_length=20)),
                ('status', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours'), ('FERMEE', 'Fermée')], default='OUVERTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiseEnRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='EN_ATTENTE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('disponibilite_debut', models.DateTimeField()),
                ('disponibilite_fin', models.DateTimeField()),
                ('modalite', models.CharField(choices=[('PRESENTIEL', 'Présentiel'), ('DISTANCIEL', 'Distanciel'), ('HYBRIDE', 'Hybride')], default='PRESENTIEL', max_length=20)),
                ('status', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours'), ('FERMEE', 'Fermée')], default='OUVERTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
