# Generated by Django 6.0.6 on 2026-06-08 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miseenrelation',
            name='demande',
        ),
        migrations.RemoveField(
            model_name='miseenrelation',
            name='offre',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='auteur',
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OFFRE', 'Offre'), ('DEMANDE', 'Demande')], max_length=10)),
                ('matiere', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('disponibilite_debut', models.DateTimeField()),
                ('disponibilite_fin', models.DateTimeField()),
                ('modalite', models.CharField(choices=[('PRESENTIEL', 'Présentiel'), ('EN_LIGNE', 'En ligne'), ('LES_DEUX', 'Les deux')], max_length=20)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours'), ('FERMEE', 'Fermée')], default='OUVERTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proposals',
            },
        ),
        migrations.DeleteModel(
            name='Demande',
        ),
        migrations.DeleteModel(
            name='MiseEnRelation',
        ),
        migrations.DeleteModel(
            name='Offre',
        ),
    ]
