# Generated by Django 6.0.6 on 2026-06-10 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OFFRE', 'Offre de mentorat'), ('DEMANDE', 'Demande de mentorat')], max_length=10)),
                ('matiere', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('disponibilite_debut', models.DateTimeField()),
                ('disponibilite_fin', models.DateTimeField()),
                ('modalite', models.CharField(choices=[('PRESENTIEL', 'Présentiel'), ('EN_LIGNE', 'En ligne'), ('LES_DEUX', 'Les deux')], max_length=15)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée'), ('EN_COURS', 'En cours')], default='OUVERTE', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
