# Generated by Django 6.0.6 on 2026-06-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('TERMINE', 'Terminé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15),
        ),
    ]
