# Generated by Django 6.0.6 on 2026-06-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_matching', '0002_matching_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='matiere',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
